// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXgsvLvoSRuTra1AqR-hZJ-Y6IJYSBxI',
    appId: '1:218854965293:web:95d222569c2d276d87f8a4',
    messagingSenderId: '218854965293',
    projectId: 'flutter-sandbox-testing',
    authDomain: 'flutter-sandbox-testing.firebaseapp.com',
    storageBucket: 'flutter-sandbox-testing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_rx8vKd0teTW2U95w-resQWWbqOvR78',
    appId: '1:218854965293:android:ae91835c2a0f8c3887f8a4',
    messagingSenderId: '218854965293',
    projectId: 'flutter-sandbox-testing',
    storageBucket: 'flutter-sandbox-testing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVWtnbIbcXv_geIzI-IwoQl1VPw4SQvp8',
    appId: '1:218854965293:ios:730318f6e6c07d0387f8a4',
    messagingSenderId: '218854965293',
    projectId: 'flutter-sandbox-testing',
    storageBucket: 'flutter-sandbox-testing.firebasestorage.app',
    iosBundleId: 'com.example.coffeeCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVWtnbIbcXv_geIzI-IwoQl1VPw4SQvp8',
    appId: '1:218854965293:ios:730318f6e6c07d0387f8a4',
    messagingSenderId: '218854965293',
    projectId: 'flutter-sandbox-testing',
    storageBucket: 'flutter-sandbox-testing.firebasestorage.app',
    iosBundleId: 'com.example.coffeeCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOXgsvLvoSRuTra1AqR-hZJ-Y6IJYSBxI',
    appId: '1:218854965293:web:d095cd0f212744b287f8a4',
    messagingSenderId: '218854965293',
    projectId: 'flutter-sandbox-testing',
    authDomain: 'flutter-sandbox-testing.firebaseapp.com',
    storageBucket: 'flutter-sandbox-testing.firebasestorage.app',
  );
}
